"""add external id to leads

Revision ID: ecbb6edd779b
Revises: 65ee8e786bf6
Create Date: 2026-07-23 12:41:03.515639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecbb6edd779b'
down_revision: Union[str, Sequence[str], None] = '65ee8e786bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_leads_external_id'), 'leads', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_external_id'), table_name='leads')
    op.drop_column('leads', 'external_id')
    # ### end Alembic commands ###
